### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by scheung38** [sparkfun/RHT03#2]
Hi, just cloned your example but upon launching RHT3_Example Arduino 1.6.5 IDE i get:

```
Build options changed, rebuilding all
RHT03_Example.ino:9:19: fatal error: reg51.h: No such file or directory
compilation terminated.
```

**Comment by urkraft** [comment]
I got the same error. As you can see from the error message - he did not include the header file that his code refers to (<reg51.h> - actually, his code also refers to another header file that is not included as well). I resolved the problem by deleting his code from my system and using Adafruit's code which you can get here:
https://github.com/adafruit/DHT-sensor-library
I suggest you do the same in order to resolve your problems.

**Comment by scheung38** [comment]
Thanks so much because I do believe in sharing problems and good information when we are not the designer of the tools,but users.

**Comment by ToniCorinne** [comment]
Hi - thanks for your feedback. We have actually created our own libraries for this product (the original sketch was from the manufacturer), and have updated the repo to include the new code. Thanks!
